### ISSUE TITLE
[EPIC] Data persistence

### ISSUE THREAD

**Issue by jackzampolin** [gordian-engine/gordian#10]
Currently goridan is implemented with [in-memory data stores](https://github.com/rollchains/gordian/tree/main/tm/tmstore/tmmemstore/). In order to have a production implemetation we need to enable persistence. SQLite support for Gordian data persistence is the first target. The tables should be all independent of one another making the translation to SQL straightforward. Initial implementation should be hand written SQL. The following interfaces need implementation for this epic.

- [ ]  `ActionStore` - [`tm/tmstore/actionstore.go`](../blob/master/tm/tmstore/actionstore.go)
- [ ]  `BlockStrore` - [`tm/tmstore/blockstore.go`](../blob/master/tm/tmstore/blockstore.go)
- [ ]  `FinalizationStore` - [`tm/tmstore/finalizationstore.go`](../blob/master/tm/tmstore/finalizationstore.go)
- [ ]  `MirrorStore` - [`tm/tmstore/mirrorstore.go`](../blob/master/tm/tmstore/mirrorstore.go)
- [ ]  `RoundStore` - [`tm/tmstore/roundstore.go`](../blob/master/tm/tmstore/roundstore.go)
- [ ]  `ValidatorStore` - [`tm/tmstore/validatorstore.go`](../blob/master/tm/tmstore/validatorstore.go)
