### ISSUE TITLE
[EPIC] Gordian GRPC

### ISSUE THREAD

**Issue by jackzampolin** [gordian-engine/gordian#13]
## External
- [ ] As a user I'd like to access gordian state via RPC/gRPC #8
- [ ] As a user I'd like to access gordian state via an RPC interface that looks like comet #3
- [ ] Make Client/Server public facing
- [ ] Allow overriding default server Impl or interfaces within so other consensus servers can be written on top
- [ ] Relayer Support
- [ ] ICT Support

## Internal
- [ ] Use within the http Server as a wrapper #14
- [ ] Migrate to buf ([reece/grpc-buf-attempt](https://github.com/rollchains/gordian/tree/reece/grpc-buf-attempt)) with grpcurl & client support
